### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by bartosh**
Code cleanup for upper level python modules (mic/*.py). As a result most of the modules have pylint rate > 8.

### CODE REVIEW

**Comment by bartosh** [comment]
Added code cleanup for mic/imager/*.py

PS: I'm on vacation till 09 Jan 2012.

**Comment by jfding** [comment]
Ed, thank you very much for your big efforts to improve the code. But I cannot accept it, because:
1. your patch is too big and includes too many different types of changes together. I hope you can split it and resubmit.
2. I noticed you have rewritten many pieces of code in nicer presentation for the same function. But I think it's too aggressive to be safe. Let's keep the workable code which was introduced from several years ago and different source. Let's change it little by little.
3. For many coding style problem in very tiny details, it's a very personal choice. In some places, let's follow our own:)

**Comment by bartosh** [comment]
I'd propose to do this a bit different way. First we need to improve unit test coverage. If it's good enough than we can get back to these changes. Does it make sense for you?

**Comment by jfding** [comment]
Sure, it sounds good. Anyway, too many changes in one big commit is not good enough:)

thanks

**Comment by bartosh** [comment]
Well, it's two commits, not just one. Never mind. I'll concentrate on testing if I have time. Closing this request.

**Pull request closed without merging**
